### ISSUE TITLE
Did you encounter an issue with S3Drive?

### ISSUE THREAD

**Issue by tomekit** [s3drive/app#21]
Please report using: [Discord support](https://discord.com/invite/YvxvypRqCu) alternatively use [Github issues](https://github.com/s3drive/app/issues)

**Comment by Morethanevil** [comment]
Discordlink is invalid tells the app 🫤

**Comment by tomekit** [comment]
@Morethanevil
Thanks for that, it's been fixed now !

**Comment by iamsaswatachakraborty** [comment]
I am encountering an issue on the S3Drivw app (exe) on Windows 11. Clicking on three dots beside folders do not open the menu unless I click on it multiple times. I have noticed this issue about a year ago when I first tried S3 Drive, then I moved on to Mega. Recently installed S3Drive (latest) and paired it with Idrive e2, and even though the app has improved a lot, this particular bug is still present. Also, pull down to refresh is very sensitive. I pulled down on the app multiple times by accident which immediately cancelled the upload/download. I wish there was a was to stop pull down to refresh action and only click on the refresh button when needed.

**Comment by tomekit** [comment]
> I am encountering an issue on the S3Drive app (exe) on Windows 11. Clicking on three dots beside folders do not open the menu unless I click on it multiple times. I have noticed this issue about a year ago when I first tried S3Drive, then I moved on to Mega. Recently installed S3Drive (latest) and paired it with Idrive e2, and even though the app has improved a lot, this particular bug is still present. Also, pull down to refresh is very sensitive. I pulled down on the app multiple times by accident which immediately cancelled the upload/download. I wish there was a way to stop pull down to refresh action and only click on the refresh button when needed.

Thank you for your feedback @iamsaswatachakraborty. Please report issues through the official channels listed here: https://github.com/s3drive/app/issues/21#issue-1588306411

<img width="1036" height="406" alt="Image" src="https://github.com/user-attachments/assets/16008488-f42b-4919-8ec4-937a68eec280" />

Regarding your Play Store review. while we understand your frustration, leaving a 1-star review for a Windows-specific issue has a significant negative impact on our revenue and slows down development. We encourage you to contact support directly before leaving a review.

Regarding:
> I don't know why this app never shows up on the Play Store when I search by the name. I need to search it on the browser and then redirect from there. That's on my Moto G32 running LOS 22.2, but on my Galaxy S23 running OneUI 7 stable, it straight away tells me that the app is not available in my country. That's weird!

S3Drive isn’t currently available in India, we’re sorry for the inconvenience.
Availability restrictions are intentional for now, and your situation illustrates why we’ve had to make this choice.

<img width="855" height="130" alt="Image" src="https://github.com/user-attachments/assets/7492956a-6e15-4e44-a7a0-beb58069167d" />
